name: myportfolio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-174.2.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  oktoast: ^3.4.0
  get_storage: ^2.1.1
  get: ^4.6.6
  responsive_builder: ^0.7.0
  font_awesome_flutter: ^10.5.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
