// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-Jfp_bPGHxzdMyU4eqpdKGjEEJs9raw',
    appId: '1:99545190852:web:8ff8dd10b8dbd590451491',
    messagingSenderId: '99545190852',
    projectId: 'myportfolio-c8591',
    authDomain: 'myportfolio-c8591.firebaseapp.com',
    storageBucket: 'myportfolio-c8591.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCee7avb_af7kkQDjERv246PJd3-XO5wDw',
    appId: '1:99545190852:android:eb91f95ea28b6e07451491',
    messagingSenderId: '99545190852',
    projectId: 'myportfolio-c8591',
    storageBucket: 'myportfolio-c8591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDve13Vk4vJ0VwBuLKVrfWN3jDmpFtgzCs',
    appId: '1:99545190852:ios:c5ba648b9e5e58e2451491',
    messagingSenderId: '99545190852',
    projectId: 'myportfolio-c8591',
    storageBucket: 'myportfolio-c8591.appspot.com',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDve13Vk4vJ0VwBuLKVrfWN3jDmpFtgzCs',
    appId: '1:99545190852:ios:1e3bd0c658251d3c451491',
    messagingSenderId: '99545190852',
    projectId: 'myportfolio-c8591',
    storageBucket: 'myportfolio-c8591.appspot.com',
    iosBundleId: 'com.example.myportfolio.RunnerTests',
  );
}
